config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'items#index'
  resources :items, only: [:index, :show]
  resources :orders, only: [:index, :show]
  resources :cart_items, only: [:create, :destroy, :update]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/dashboard', to: 'users#show'
  resources :users

  get '/admin/dashboard', to: 'admin/users#show'
  namespace :admin do
    resources :users, only: [:show, :update]
    resources :orders, only: [:update]
    resources :items, only: [:create, :new]
  end

  get '/cart', to: 'cart#index', as: 'cart'
  post '/cart', to: 'orders#create'
  get '/:category_name', to: 'categories#show', as: 'category'
end

app/models/cart.rb
class Cart
  attr_reader :contents

  def initialize(initial_content = {})
    @contents = initial_content || {}
  end

  def add_item(item_id)
    @contents[item_id.to_s] ||= 0
    @contents[item_id.to_s] += 1
  end

  def remove_item(item_id)
    @contents.delete item_id.to_s
  end

  def change_quantity(item_id, quantity)
    @contents[item_id.to_s] = if quantity.to_i <= 0
                                0
                              else
                                quantity.to_i
                              end
  end

  def item_quantities
    result = {}
    @contents.each do |item_id, quantity|
      result[Item.find(item_id)] = quantity
    end
    result
  end

  def empty_message
    'False Start!  You have nothing in your cart!'
  end

  def total
    item_quantities.reduce(0) do |total, content|
      total += content.first.price * content.last
    end
  end

  def empty
    @contents = {}
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def index
  end
end

app/views/cart/index.html.erb
<div class='container'>
<div id='cart'>
  <% if @cart.item_quantities.empty? %>
    <%= @cart.empty_message %>
  <% else %>
    <% @cart.item_quantities.each do |item, quantity| %>
      <%= render partial: 'shared/item_list', locals: { item: item } %>
      <div class='row'>
        <div class='col-md-4'>
          Number in cart: <%= quantity %>
          <%= form_for :cart_items, url: cart_item_path(item), method: 'put' do |f|  %>
          <div class="field">
            <%= f.label "Update Quantity:"  %>
            <%= f.number_field :quantity, value: "#{quantity}" %>
            <%= f.submit "Update Item"%>
          </div>
          <% end %>
        </div>
        <div class='col-md-4'>
          <%= link_to 'Remove', cart_item_path(item), method: 'delete' %>
        </div>
        <div class='col-md-4'>
          Subtotal: <%= number_to_currency(item.price * quantity) %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>
<div style='float:right'>
<h3>Total: <%= number_to_currency @cart.total %></h3>
<% if current_user %>
  <%= button_to 'Checkout' %>
<% else %>
  <%= link_to 'Login or Create Account to Checkout', login_path %>
<% end %>
</div>
</div>