config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'items#index'
  resources :items, only: [:index, :show]
  resources :orders, only: [:index, :show]
  resources :cart_items, only: [:create, :destroy, :update]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/dashboard', to: 'users#show'
  resources :users

  get '/admin/dashboard', to: 'admin/users#show'
  namespace :admin do
    resources :users, only: [:show, :update]
    resources :orders, only: [:update]
    resources :items, only: [:create, :new]
  end

  get '/cart', to: 'cart#index', as: 'cart'
  post '/cart', to: 'orders#create'
  get '/:category_name', to: 'categories#show', as: 'category'
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :orders

  validates_confirmation_of :password
  validates :username, presence: true, uniqueness: true
  validates :name, presence: true
  validates :address, presence: true

  enum role: %w(default admin)
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  def show
    @orders = Order
    @status = params[:status] || 'all'
    if current_admin?
      render :show
    else
      flash.now[:warning] = 'Encroachment! Admin Dashboard is for admins only!'
      render 'shared/error'
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to dashboard_path
    else
      render :new
    end
  end

  def edit
    if !current_user
      flash[:warning] = 'Must be logged in to edit your profile'
      redirect_to login_path
    elsif @user == current_user

    else
      flash.now[:warning] = 'Users can only edit their own profile'
      render 'shared/error'
    end
  end

  def update
    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  def show
    if !current_user
      flash[:warning] = 'Must log in to view dashboard'
      redirect_to login_path
    elsif @user == current_user || current_admin?
      render :show
    else
      flash.now[:warning] = 'Users can only view their own dashboard'
      render 'shared/error'
    end
  end

  private

  def user_params
    params.require(:user).permit(:username,
                                 :name,
                                 :address,
                                 :password,
                                 :password_confirmation)
  end

  def set_user
    @user = if params[:id]
              User.find(params[:id])
            else
              current_user
            end
  end
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>

<% if @user.errors.any? %>
  <h2><%= pluralize(@user.errors.count, "error") %> prohibited this record from being saved:</h2>
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

  <%= f.label :username %>
  <%= f.text_field :username %> <br />
  <%= f.label :name %>
  <%= f.text_field :name %> <br />
  <%= f.label :address %>
  <%= f.text_field :address %> <br />

  <%= f.label :password %>
  <%= f.password_field :password %> <br />
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit %>
<% end %>

app/views/users/edit.html.erb
<h1> Edit your account! <h1>

<%= render partial: "form" %>

app/views/users/new.html.erb
<%= render partial: "form" %>

app/views/users/show.html.erb
<h1>Welcome <%= @user.username %></h1>

<h3><%= link_to 'View Cart', cart_path %></h3>
<h3><%= link_to 'View past orders', orders_path %></h3>
<h3><%= link_to 'Edit Profile', edit_user_path(@user) %><h3>
<% if current_admin? %>
  <h3><%= link_to 'Admin Dashboard', admin_dashboard_path %></h3>
<% end %>
<p>Member since <%= @user.created_at %></p>