config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'items#index'
  resources :items, only: [:index, :show]
  resources :orders, only: [:index, :show]
  resources :cart_items, only: [:create, :destroy, :update]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/dashboard', to: 'users#show'
  resources :users

  get '/admin/dashboard', to: 'admin/users#show'
  namespace :admin do
    resources :users, only: [:show, :update]
    resources :orders, only: [:update]
    resources :items, only: [:create, :new]
  end

  get '/cart', to: 'cart#index', as: 'cart'
  post '/cart', to: 'orders#create'
  get '/:category_name', to: 'categories#show', as: 'category'
end

app/views/shared/_item_list.html.erb
<div class='row'>
  <div class='col-md-6 img-responsive'>
    <%= link_to image_tag(item.image), item_path(item) %>
  </div>
  <div class='col-md-6'>
    <ul>
      <li>Name: <%= link_to item.title, item_path(item) %></li>
      <li>Description: <%= item.description %></li>
      <li>Price: <%= number_to_currency item.price %></li>
      <h4>Categories:</h4>
      <% item.categories.each do |category| %>
      <li><%= link_to category.name, category_path(category) %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_nav_bar.html.erb
<nav class='navbar navbar-inverse'>
  <div class='container-fluid'>
    <div class='navbar-header'>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <ul class='nav navbar-nav navbar-right'>
      <li><%= link_to 'View Cart', cart_path %></li>
      <% if current_user %>
        <li><%= link_to "Logged in as #{current_user.username}",
         dashboard_path%></li>
        <li><%= link_to 'Logout', logout_path, method: 'delete'%></li>
      <% else %>
        <li><%= link_to 'Login', login_path %>
      <% end %>
    </ul>
  </div>
</nav>

app/views/shared/error.html.erb
<div class='jumbotron'>
  <h1>Flag on the play</h1>
</div>