config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'items#index'
  resources :items, only: [:index, :show]
  resources :orders, only: [:index, :show]
  resources :cart_items, only: [:create, :destroy, :update]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/dashboard', to: 'users#show'
  resources :users

  get '/admin/dashboard', to: 'admin/users#show'
  namespace :admin do
    resources :users, only: [:show, :update]
    resources :orders, only: [:update]
    resources :items, only: [:create, :new]
  end

  get '/cart', to: 'cart#index', as: 'cart'
  post '/cart', to: 'orders#create'
  get '/:category_name', to: 'categories#show', as: 'category'
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :orders

  validates_confirmation_of :password
  validates :username, presence: true, uniqueness: true
  validates :name, presence: true
  validates :address, presence: true

  enum role: %w(default admin)
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  def show
    @orders = Order
    @status = params[:status] || 'all'
    if current_admin?
      render :show
    else
      flash.now[:warning] = 'Encroachment! Admin Dashboard is for admins only!'
      render 'shared/error'
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to dashboard_path
    else
      render :new
    end
  end

  def edit
    if !current_user
      flash[:warning] = 'Must be logged in to edit your profile'
      redirect_to login_path
    elsif @user == current_user

    else
      flash.now[:warning] = 'Users can only edit their own profile'
      render 'shared/error'
    end
  end

  def update
    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  def show
    if !current_user
      flash[:warning] = 'Must log in to view dashboard'
      redirect_to login_path
    elsif @user == current_user || current_admin?
      render :show
    else
      flash.now[:warning] = 'Users can only view their own dashboard'
      render 'shared/error'
    end
  end

  private

  def user_params
    params.require(:user).permit(:username,
                                 :name,
                                 :address,
                                 :password,
                                 :password_confirmation)
  end

  def set_user
    @user = if params[:id]
              User.find(params[:id])
            else
              current_user
            end
  end
end

app/views/admin/users/_filter_button.html.erb
<button class="btn btn-secondary dropdown-toggle"
        type="button" id="filter_status" data-toggle="dropdown"
        aria-haspopup="true" aria-expanded="false">
  Filter Status
</button>
<div class="dropdown-menu" aria-labelledby="filter_status">
  <a class="dropdown-item" href="?status=all">All</a></br>
  <a class="dropdown-item" href="?status=ordered">Ordered</a></br>
  <a class="dropdown-item" href="?status=paid">Paid</a></br>
  <a class="dropdown-item" href="?status=completed">Completed</a></br>
  <a class="dropdown-item" href="?status=cancelled">Cancelled</a>
</div>

app/views/admin/users/_status_count.html.erb
<table>
  <tr>
    <th>Status</th><th>Count</th>
  </tr>
  <tr>
    <td>Ordered</td><td> <%= @orders.count_by_status('ordered') %></td>
  </tr>
  <tr>
    <td>Paid</td><td> <%= @orders.count_by_status('paid') %></td>
  </tr>
  <tr>
    <td>Completed</td><td> <%= @orders.count_by_status('completed') %></td>
  </tr>
  <tr>
    <td>Cancelled</td><td> <%= @orders.count_by_status('cancelled') %></td>
  </tr>
</table>

app/views/admin/users/show.html.erb
<div class='row'>
  <div class='col-md-6'>
    <h3> Admin Dashboard </h3>

    <h1>Welcome <%= current_user.username %></h1>
    <h3><%= link_to 'Create item', new_admin_item_path %></h3>
  </div>
  <div class ='col-md-6'>
    <%= render partial: 'status_count', locals: {orders: @orders} %>
  </div>
</div>

<div class='row'>
  <div class='col-md-8 text-center'><h3>Orders</h3></div>
  <div class="col-md-4 dropdown">
  <%= render partial: 'filter_button' %>
</div>

<div class='row'>
  <div class='col-md-12'>
    <table>
      <% @orders.all_by_status(@status).each do |order| %>
        <tr class='<%= "order#{order.id}" %>' >
          <td><%= link_to "Order number #{order.id}", order_path(order) %></td>
          <% if order.ordered? %>
            <td>
              <%= link_to 'Cancel', admin_order_path(order.id, 'order[status]' => 'cancelled'), method: :put %>
              <!-- , :order[:status] => 2 -->
            </td>
            <td>
              <%= link_to 'Mark as paid', admin_order_path(order.id, 'order[status]' => 'paid'), method: :put %>
            </td>
          <% elsif order.paid? %>
            <td>
              <%= link_to 'Cancel', admin_order_path(order.id, 'order[status]' => 'cancelled'), method: :put %>
            </td>
            <td>
              <%= link_to 'Mark as completed', admin_order_path(order.id, 'order[status]' => 'completed'), method: :put %>
            </td>
          <% end %>
        </tr>
      <% end %>
    </table>
  </div>
</div>